#!/bin/bash

cd $(dirname $0)

minLines=10000
N=3
for f in *.simulate *.sh; do
	folder=${f%.*}
	if [ ! -d $folder ]; then
		mkdir $folder
	fi

	printf "%22s " $folder
	tRuns=1000000
	for i in $(seq 1 $N); do
		start=`date +%s.%N`
		bash $f > /dev/null
		end=`date +%s.%N`

		printf "."
		ti=$(echo "$end - $start" | bc -l)

		# smallest time = fewest background task
		[[ $(echo "$ti < $tRuns" | bc -l) -eq 1 ]] && tRuns=$ti
	done

	printf " %8.2fs\n" $tRuns
	echo "$tRuns" >> $folder/times
	l=$(wc -l $folder/times | awk '{print $1}')
	minLines=$((minLines > l ? l : minLines))
done

for f in */times; do
	# Add run-name and shorten to length of shortest time-list
	echo $(dirname $f) > tmp
	tail -n +2 $f | tail -n $((minLines-1)) >> tmp
	cp tmp $f
done

paste */times | awk '{if (NR == 1) {printf "%s\tTotal\n", $0;} else {t = 0; for(i = 1; i <= NF; i++) {t += $i; printf "%4.2f\t", $i} printf "%4.2f\n", t}}' > performanceTable

awk -f stats.awk performanceTable || exit 1
