#! /bin/bash

compare() {
    echo "Comparing reference ATLAS-files to new ones"
    for a in ATLAS_*; do
	if [[ $a == *.bai ]]; then continue; fi
	if [[ $a == *.bam ]]; then
	    command -v samtools > /dev/null || continue

	    if ! diff -q <(samtools view $a) <(samtools view ../${fo}_ref/$a); then
		differs=true
	    fi
	fi
	if ! diff -q $a ../${fo}_ref/$a; then
	    differs=true
	fi
    done
    if [[ ! $differs ]]; then
	echo "All files are identical"
    fi
}

for f in *.sh; do (
    fo=${f%.sh}
    echo "Regresision Test: $fo"
    if [[ ! -d ${fo}_ref ]]; then
	echo "Creating reference ATLAS-files in folder ${fo}_ref"
	mkdir -v ${fo}_ref
	cd ${fo}_ref
	bash ../$f > out 2> eout
    else
	echo "Found reference ATLAS-files in folder ${fo}_ref"
	if [[ ! -d ${fo}_new ]]; then
	    echo "Creating new ATLAS-files in folder ${fo}_new"
	    mkdir -v ${fo}_new
	    cd ${fo}_new
	    bash ../$f > out 2> eout
	else
	    echo "Found new ATLAS-files in folder ${fo}_new"
	    cd ${fo}_new
	fi

	compare
    fi
    echo
) done
