#! /bin/bash

compare() {
    echo "Comparing reference ATLAS-files to new ones"
    local differs=""
    for a in ATLAS_*; do
	[[ $a == *.bai ]] && continue
	if [[ $a == *.bam ]]; then
	    command -v samtools > /dev/null || continue
	    ! diff -q <(samtools view $a) <(samtools view ../${fo}_ref/$a) && differs=true
	fi
	! diff -q $a ../${fo}_ref/$a &&  differs=true
    done
    [[ $differs ]] && return 1
    echo "All files are identical"
}

err=0
for f in *.sh; do
    fo=${f%.sh}
    echo "Regresision Test: $fo"
    if [[ ! -d ${fo}_ref ]]; then
	echo "Creating reference ATLAS-files in folder ${fo}_ref"
	mkdir -v ${fo}_ref
	cd ${fo}_ref
	bash ../$f > out 2> eout
	[[ -s eout ]] && echo "Reference simulation of $fo ended with errors"; cat eout
    else
	echo "Found reference ATLAS-files in folder ${fo}_ref"
	if [[ ! -d ${fo}_new ]]; then
	    echo "Creating new ATLAS-files in folder ${fo}_new"
	    mkdir -v ${fo}_new
	    cd ${fo}_new
	    bash ../$f > out 2> eout
	    [[ -s eout ]] && echo "New simulation of $fo ended with errors"; cat eout
	else
	    echo "Found new ATLAS-files in folder ${fo}_new"
	    cd ${fo}_new
	fi

	! compare && err=1
    fi
    cd ..
    echo
done

exit $err
