#!/bin/bash

# Runs VCF-simulator with some default arguments for all examples.
# Additional arguments can be passed.

. $(dirname $0)/find_atlas

out="simulate"
$atlas --task simulate --vcf --type HW \
	   --chrLength 11111,5432,12345 --depth 2,5,8 --ploidy 2,1,2 \
	   --out $out --logFile $out.out  "$@" 2> $out.eout
