#!/bin/bash

cd $(dirname $0)

file=performanceTable

# First time
for f in *.simulate *.sh; do
	folder=${f%.*}
	if [ ! -d $folder ]; then
		mkdir $folder
		echo $folder > $folder/times
	fi
done

for f in *.simulate *.sh; do
	folder=${f%.*}
	ext=${f#*.}
	N=2

	printf "%20s " $folder
	tRuns=1000000
	for i in $(seq 1 $N); do
		start=`date +%s.%N`
		bash $f > /dev/null
		end=`date +%s.%N`

		printf "."
		ti=$(echo "$end - $start" | bc -l)
		[[ $(echo "$ti < $tRuns" | bc -l) -eq 1 ]] && tRuns=$ti  # smallest time = fewest background task
	done
	printf " %8.2fs\n" $tRuns
	echo "$tRuns" >> $folder/times
done

paste */times | awk '{if (NR == 1) {printf "%s\tTotal\n", $0;} else {t = 0; for(i = 1; i <= NF; i++) {t += $i; printf "%4.2f\t", $i} printf "%4.2f\n", t}}' > performanceTable

awk -f stats.awk performanceTable || exit 1
